#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ScnDiscounts.Droid.Resource", IsApplication=true)]

namespace ScnDiscounts.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::ScnDiscounts.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::ScnDiscounts.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int adSize = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int adSizes = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int adUnitId = 2130771970;
			
			// aapt resource value: 0x7f010016
			public const int appTheme = 2130771990;
			
			// aapt resource value: 0x7f01001d
			public const int buyButtonAppearance = 2130771997;
			
			// aapt resource value: 0x7f01001a
			public const int buyButtonHeight = 2130771994;
			
			// aapt resource value: 0x7f01001c
			public const int buyButtonText = 2130771996;
			
			// aapt resource value: 0x7f01001b
			public const int buyButtonWidth = 2130771995;
			
			// aapt resource value: 0x7f010007
			public const int cameraBearing = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int cameraTargetLat = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int cameraTargetLng = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int cameraTilt = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int cameraZoom = 2130771979;
			
			// aapt resource value: 0x7f010005
			public const int circleCrop = 2130771973;
			
			// aapt resource value: 0x7f010017
			public const int environment = 2130771991;
			
			// aapt resource value: 0x7f010019
			public const int fragmentMode = 2130771993;
			
			// aapt resource value: 0x7f010018
			public const int fragmentStyle = 2130771992;
			
			// aapt resource value: 0x7f010004
			public const int imageAspectRatio = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int imageAspectRatioAdjust = 2130771971;
			
			// aapt resource value: 0x7f01000c
			public const int liteMode = 2130771980;
			
			// aapt resource value: 0x7f010006
			public const int mapType = 2130771974;
			
			// aapt resource value: 0x7f010020
			public const int maskedWalletDetailsBackground = 2130772000;
			
			// aapt resource value: 0x7f010022
			public const int maskedWalletDetailsButtonBackground = 2130772002;
			
			// aapt resource value: 0x7f010021
			public const int maskedWalletDetailsButtonTextAppearance = 2130772001;
			
			// aapt resource value: 0x7f01001f
			public const int maskedWalletDetailsHeaderTextAppearance = 2130771999;
			
			// aapt resource value: 0x7f010024
			public const int maskedWalletDetailsLogoImageType = 2130772004;
			
			// aapt resource value: 0x7f010023
			public const int maskedWalletDetailsLogoTextColor = 2130772003;
			
			// aapt resource value: 0x7f01001e
			public const int maskedWalletDetailsTextAppearance = 2130771998;
			
			// aapt resource value: 0x7f01000d
			public const int uiCompass = 2130771981;
			
			// aapt resource value: 0x7f010015
			public const int uiMapToolbar = 2130771989;
			
			// aapt resource value: 0x7f01000e
			public const int uiRotateGestures = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int uiScrollGestures = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int uiTiltGestures = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int uiZoomControls = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int uiZoomGestures = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int useViewLifecycle = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int zOrderOnTop = 2130771988;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060009
			public const int common_action_bar_splitter = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int common_signin_btn_dark_text_default = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int common_signin_btn_dark_text_disabled = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_signin_btn_dark_text_focused = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_signin_btn_dark_text_pressed = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int common_signin_btn_default_background = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int common_signin_btn_light_text_default = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int common_signin_btn_light_text_disabled = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_signin_btn_light_text_focused = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int common_signin_btn_light_text_pressed = 2131099653;
			
			// aapt resource value: 0x7f060017
			public const int common_signin_btn_text_dark = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int common_signin_btn_text_light = 2131099672;
			
			// aapt resource value: 0x7f06000f
			public const int wallet_bright_foreground_disabled_holo_light = 2131099663;
			
			// aapt resource value: 0x7f06000a
			public const int wallet_bright_foreground_holo_dark = 2131099658;
			
			// aapt resource value: 0x7f060010
			public const int wallet_bright_foreground_holo_light = 2131099664;
			
			// aapt resource value: 0x7f06000c
			public const int wallet_dim_foreground_disabled_holo_dark = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int wallet_dim_foreground_holo_dark = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int wallet_dim_foreground_inverse_disabled_holo_dark = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int wallet_dim_foreground_inverse_holo_dark = 2131099661;
			
			// aapt resource value: 0x7f060014
			public const int wallet_highlighted_text_holo_dark = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int wallet_highlighted_text_holo_light = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int wallet_hint_foreground_holo_dark = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int wallet_hint_foreground_holo_light = 2131099665;
			
			// aapt resource value: 0x7f060015
			public const int wallet_holo_blue_light = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int wallet_link_text_light = 2131099670;
			
			// aapt resource value: 0x7f060019
			public const int wallet_primary_text_holo_light = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int wallet_secondary_text_holo_dark = 2131099674;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_ic_googleplayservices = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_signin_btn_icon_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_signin_btn_icon_disabled_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_disabled_focus_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_disabled_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_focus_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_focus_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_normal_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_normal_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_pressed_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_pressed_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_text_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_text_disabled_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_text_disabled_focus_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_disabled_focus_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_disabled_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_focus_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_focus_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_normal_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_normal_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_pressed_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_pressed_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int discount_label = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_about = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_detail = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_empty = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_location = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_logo = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_map = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_marker_distance = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_menu = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_menu_about = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_menu_back = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_menu_phone = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_pin = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_pin_blue = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_pin_green = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_pin_grey = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_pin_navigation = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic_pin_orange = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic_pin_purple = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic_pin_rose = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic_pin_yellow = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ic_plusone_medium_off_client = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ic_plusone_small_off_client = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ic_plusone_standard_off_client = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ic_plusone_tall_off_client = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ic_settings = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic_tag = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int Icon = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int img_background = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int img_empty_big = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int img_empty_small = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int img_logo = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int list_border = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int powered_by_google_dark = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int powered_by_google_light = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int test = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int test_image_64x64 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int test_image_big = 2130837567;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int adjust_height = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int adjust_width = 2131230721;
			
			// aapt resource value: 0x7f080010
			public const int book_now = 2131230736;
			
			// aapt resource value: 0x7f08000c
			public const int buyButton = 2131230732;
			
			// aapt resource value: 0x7f080011
			public const int buy_now = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int buy_with_google = 2131230738;
			
			// aapt resource value: 0x7f080014
			public const int classic = 2131230740;
			
			// aapt resource value: 0x7f080013
			public const int donate_with_google = 2131230739;
			
			// aapt resource value: 0x7f080015
			public const int grayscale = 2131230741;
			
			// aapt resource value: 0x7f080007
			public const int holo_dark = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int holo_light = 2131230728;
			
			// aapt resource value: 0x7f080003
			public const int hybrid = 2131230723;
			
			// aapt resource value: 0x7f08000e
			public const int match_parent = 2131230734;
			
			// aapt resource value: 0x7f080016
			public const int monochrome = 2131230742;
			
			// aapt resource value: 0x7f080002
			public const int none = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int normal = 2131230724;
			
			// aapt resource value: 0x7f080009
			public const int production = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int sandbox = 2131230730;
			
			// aapt resource value: 0x7f080005
			public const int satellite = 2131230725;
			
			// aapt resource value: 0x7f08000d
			public const int selectionDetails = 2131230733;
			
			// aapt resource value: 0x7f08000b
			public const int strict_sandbox = 2131230731;
			
			// aapt resource value: 0x7f080006
			public const int terrain = 2131230726;
			
			// aapt resource value: 0x7f08000f
			public const int wrap_content = 2131230735;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f030000
			public const int gtm_analytics = 2130903040;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050024
			public const int ApplicationName = 2131034148;
			
			// aapt resource value: 0x7f050023
			public const int Hello = 2131034147;
			
			// aapt resource value: 0x7f050002
			public const int accept = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int common_android_wear_notification_needs_update_text = 2131034121;
			
			// aapt resource value: 0x7f050016
			public const int common_android_wear_update_text = 2131034134;
			
			// aapt resource value: 0x7f050014
			public const int common_android_wear_update_title = 2131034132;
			
			// aapt resource value: 0x7f050012
			public const int common_google_play_services_enable_button = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int common_google_play_services_enable_text = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int common_google_play_services_enable_title = 2131034128;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_error_notification_requested_by_msg = 2131034123;
			
			// aapt resource value: 0x7f05000f
			public const int common_google_play_services_install_button = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_install_text_phone = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int common_google_play_services_install_text_tablet = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_install_title = 2131034124;
			
			// aapt resource value: 0x7f05001a
			public const int common_google_play_services_invalid_account_text = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int common_google_play_services_invalid_account_title = 2131034137;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_needs_enabling_title = 2131034122;
			
			// aapt resource value: 0x7f050018
			public const int common_google_play_services_network_error_text = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int common_google_play_services_network_error_title = 2131034135;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_notification_needs_installation_title = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_notification_needs_update_title = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_notification_ticker = 2131034118;
			
			// aapt resource value: 0x7f05001b
			public const int common_google_play_services_unknown_issue = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public const int common_google_play_services_unsupported_text = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int common_google_play_services_unsupported_title = 2131034140;
			
			// aapt resource value: 0x7f05001e
			public const int common_google_play_services_update_button = 2131034142;
			
			// aapt resource value: 0x7f050015
			public const int common_google_play_services_update_text = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int common_google_play_services_update_title = 2131034131;
			
			// aapt resource value: 0x7f050021
			public const int common_open_on_phone = 2131034145;
			
			// aapt resource value: 0x7f05001f
			public const int common_signin_button_text = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int common_signin_button_text_long = 2131034144;
			
			// aapt resource value: 0x7f050005
			public const int create_calendar_message = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int create_calendar_title = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int decline = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int store_picture_message = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int store_picture_title = 2131034112;
			
			// aapt resource value: 0x7f050022
			public const int wallet_buy_button_place_holder = 2131034146;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int AppTheme = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Theme_IAPTheme = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int WalletFragmentDefaultButtonTextAppearance = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int WalletFragmentDefaultDetailsHeaderTextAppearance = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int WalletFragmentDefaultDetailsTextAppearance = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int WalletFragmentDefaultStyle = 2130968581;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] WalletFragmentOptions = new int[] {
					2130771990,
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 0
			public const int WalletFragmentOptions_appTheme = 0;
			
			// aapt resource value: 1
			public const int WalletFragmentOptions_environment = 1;
			
			// aapt resource value: 3
			public const int WalletFragmentOptions_fragmentMode = 3;
			
			// aapt resource value: 2
			public const int WalletFragmentOptions_fragmentStyle = 2;
			
			public static int[] WalletFragmentStyle = new int[] {
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004};
			
			// aapt resource value: 3
			public const int WalletFragmentStyle_buyButtonAppearance = 3;
			
			// aapt resource value: 0
			public const int WalletFragmentStyle_buyButtonHeight = 0;
			
			// aapt resource value: 2
			public const int WalletFragmentStyle_buyButtonText = 2;
			
			// aapt resource value: 1
			public const int WalletFragmentStyle_buyButtonWidth = 1;
			
			// aapt resource value: 6
			public const int WalletFragmentStyle_maskedWalletDetailsBackground = 6;
			
			// aapt resource value: 8
			public const int WalletFragmentStyle_maskedWalletDetailsButtonBackground = 8;
			
			// aapt resource value: 7
			public const int WalletFragmentStyle_maskedWalletDetailsButtonTextAppearance = 7;
			
			// aapt resource value: 5
			public const int WalletFragmentStyle_maskedWalletDetailsHeaderTextAppearance = 5;
			
			// aapt resource value: 10
			public const int WalletFragmentStyle_maskedWalletDetailsLogoImageType = 10;
			
			// aapt resource value: 9
			public const int WalletFragmentStyle_maskedWalletDetailsLogoTextColor = 9;
			
			// aapt resource value: 4
			public const int WalletFragmentStyle_maskedWalletDetailsTextAppearance = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
