//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCNDISC.Web.Admin.Controls {
    
    
    public partial class Contacts {
        
        /// <summary>
        /// uxRemove control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton uxRemove;
        
        /// <summary>
        /// uxAdd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton uxAdd;
        
        /// <summary>
        /// uxContact1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCNDISC.Web.Admin.Controls.Contact uxContact1;
        
        /// <summary>
        /// uxContact2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCNDISC.Web.Admin.Controls.Contact uxContact2;
        
        /// <summary>
        /// uxContact3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCNDISC.Web.Admin.Controls.Contact uxContact3;
        
        /// <summary>
        /// uxContact4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCNDISC.Web.Admin.Controls.Contact uxContact4;
        
        /// <summary>
        /// uxContact5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCNDISC.Web.Admin.Controls.Contact uxContact5;
        
        /// <summary>
        /// uxContact6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCNDISC.Web.Admin.Controls.Contact uxContact6;
        
        /// <summary>
        /// uxContact7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCNDISC.Web.Admin.Controls.Contact uxContact7;
        
        /// <summary>
        /// uxContact8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCNDISC.Web.Admin.Controls.Contact uxContact8;
        
        /// <summary>
        /// uxContact9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCNDISC.Web.Admin.Controls.Contact uxContact9;
        
        /// <summary>
        /// uxContact10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SCNDISC.Web.Admin.Controls.Contact uxContact10;
    }
}
